name: Android CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (necessary for building Android projects)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: reactivecircus/android-sdk-actions@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # Step 4: Install dependencies
      - name: Install dependencies
        run: ./gradlew dependencies

      # Step 5: Build the project (you can also add tests here, but we are focusing on building)
      - name: Build APK (Debug Build)
        run: ./gradlew assembleDebug

      # Step 6: Upload APK as an artifact (optional, for debugging)
      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

